### ISSUE TITLE
There is a bug in the IPC mechanism

### ISSUE THREAD

**Issue by dayongi** [thibaultcha/lua-resty-mlcache#120]
Here is an example of how I initialize mlcache during the `init_worker` phase:
```lua
...
function _M.init_worker(opts)

    local worker_events = require("resty.worker.events")

    local err
    mlcache_obj, err = mlcache.new(
        "caches",
        "cache_main",
        {
            lru_size  = 10240,
            ttl       = 0,
            neg_ttl   = 30,
            shm_miss  = "cache_miss",
            shm_locks = "cache_lock",
            ipc = {
                register_listeners = function(events)
                    for _, event_t in pairs(events) do
                        worker_events.register(function(data)
                            event_t.handler(data)
                        end, CHANNEL_NAME, event_t.channel)
                    end
                end,
                broadcast = function(channel, data)
                    local ok, err = worker_events.post(CHANNEL_NAME, channel, data)
                    if not ok then
                        log_error( "failed to post event '", CHANNEL_NAME, "', '",
                                channel, "': ", err)
                    end
                end
            }
        }
    )
    if not mlcache_obj then
        ngx.log(ngx.ERR, "failed to initialize mlcache: ", err)
        return
    end

    mlcache_obj.set("routes", default_settings, {})
end
...
```
In daily use, the above code is no problem, but when the data in mlcache is modified through the program call result, there will be data inconsistency; after printing the "hit_level" when calling the "mlcache.get()" method It is found that the data synchronization between multiple processes has not been completed. For example: For example, I added 10 times in 1 second through the interface. It is possible that the first event has not been broadcast to other processes. My second The new request comes over. At this time, it may be that a new process has not changed the data in time. At this time, the read data is old, and the data of the first new request will be overwritten, and it keeps repeating like this. And I found that it is also used in Kong, haven't you found this problem?

**Comment by thibaultcha** [comment]
The `set` method should not be used like this. All updates must be done through the `get()` L3 callback.

**Comment by thibaultcha** [comment]
Also Kong does not use lua-resty-worker-events for workers synchronization, partly for this reason I believe. mlcache is not meant to solve workers synchronization entirely on its own,which is why the `broadcast` and `register_listener` handlers are exposed. If you wish to use `set` *and* have strong sync requirements, use an appropriate IPC library.
