### ISSUE TITLE
there are situations where the l1_serializer callback function may not be invoked

### ISSUE THREAD

**Issue by ytlm** [thibaultcha/lua-resty-mlcache#122]
when the **get_shm_set_lru** function returns at [L558](https://github.com/thibaultcha/lua-resty-mlcache/blob/main/lib/resty/mlcache.lua#L558) or  [L577](https://github.com/thibaultcha/lua-resty-mlcache/blob/main/lib/resty/mlcache.lua#L577), the **l1_serializer** callback function is not invoked

**Comment by thibaultcha** [comment]
This should be fixed in 2.6.1. Thanks for the report!
