### ISSUE TITLE
[feature] implement a `get_stale` option

### ISSUE THREAD

**Issue by thibaultcha** [thibaultcha/lua-resty-mlcache#50]
when `true`, in the case an L3 callback error occurred (impossible to fetch the value from DB, or other), then `:get()` could look into the shm and return a stale value nonetheless.

**Comment by jdesgats** [comment]
I was working on exactly that feature last week! One thing I noticed is that trying to `:get()` a stale value on a shared dict evict it instantly if the value is found to be expired.

I have a "working" branch on our internal mirror. I did not made a PR yet as it hasn't been battle tested in production for now, but I can upload the branch on my fork more quickly if you want.

**Comment by thibaultcha** [comment]
Ha, great!

I was thinking of using `ngx.shared:get_stale()` (and going through the ngx_lua code to double check all assumptions this issue is making).

If you are able to upload your branch it might give us a starting point :)

**Comment by thibaultcha** [comment]
Also, this probably should be the default behaviour, but proposed as a default here only because I am not sure of the possible ways it could be breaking yet.

**Comment by jdesgats** [comment]
Here you go: https://github.com/jdesgats/lua-resty-mlcache/tree/stale-data

I didn't made that the default behaviour, you have to give a `stale_ttl` to make it work. And stale data is signalled as being the level 4. I thought it was better as in practice the caller don't care too much about timeouts and such like that, so no need to disrupt the normal workflow.

It also behaves differently between the `nil, err` case that is more for expected errors, and the runtime error case which is more for totally unexpected things (no stale data handling in that case).

**Comment by thibaultcha** [comment]
Interesting approach, thanks for sharing. Personally I'll need more time to think of possible approaches here. Let me know of any finding if you happen to try this in production!

**Comment by thibaultcha** [comment]
> It also behaves differently between the nil, err case that is more for expected errors, and the runtime error case which is more for totally unexpected things (no stale data handling in that case).

Yes that makes sense.

**Comment by thibaultcha** [comment]
I've given this a try yesterday, and came up with a slightly different solution. Worried about the increasing complexity of the `:get()` function and all of its options, and trying to follow a default behaviour that is likely to be always the desired one (i.e. making this library as resilient as possible), I am implementing something like this:

```lua
local data, err, hit_lvl, stale = cache:get("key", opts, callback_fn)
if err then
  if not stale then
    -- error (L3 cb or other)
  end

  -- there was an error running the L3 cb but we still got the data
  -- here, hit_lvl is always 2 (no stale data saved in LRU)
end
```

Everytime we resurrect such a stale value, mlcache will re-insert it (resurrect) with `ttl = 0` (forever) *only in the shm* (no L1 cache), **but** will try to run the L3 callback on subsequent calls, in case a callback successfully runs, and we can replace the stale value with a more up-to-date one. When an application detects that a key is being served as stale, it can decide to act in its callbacks, and increase/reduce timeout values, etc...

This prevents a hot, but stale value from being evicted because it reached its `stale_ttl`, thus I believe provides a better resiliency, without sacrificing the complexity of the library from a user's POV.

What do you think?

**Comment by thibaultcha** [comment]
I gave a stab at this in #51 if you are curious @jdesgats

Also, cc @Tieske, if you still follow the development over here.

Reviews appreciated (of the code, but also the general approach and rationale behind it)

**Comment by thibaultcha** [comment]
@jdesgats Hi there,

Have you had time to look at #51? I was wondering how you would compare it to the `stale_ttl` option for your use-case? Let me know if you can allocate some time to it. Thanks!

**Comment by thibaultcha** [comment]
Done in #52 in a backwards-compatible fashion. cc @jdesgats and sorry for the huge delay! Releasing 2.2.0 now.
