### ISSUE TITLE
Not seeing level 1 cached

### ISSUE THREAD

**Issue by cloudspeech** [thibaultcha/lua-resty-mlcache#63]
Hi,

I'm using openresty/1.13.6.1.

I installed mlcache via luarocks.

lru_size is 1500, and I use cache:get with no options and a socket-fetching callback.

I initialize in init_by_lua_file and share via global 'cache' variable.

Everything works but I invariably get one L3 hit, from then on only L2 hits.

Never L1 hits.

What could be the reason?

Cheers, Markus

**Comment by Tieske** [comment]
Hard to say just from this description, can you share the code?

**Comment by cloudspeech** [comment]
Never mind, I figured it out: the nginx location in which Lua accesses the mlcache via get needs to have

`lua_code_cache on;`

for L1 caching to work!

Maybe this is worth mentioning in the docs as a potential pitfall, as it is common to have the Lua code cache set to off during development?!!

**Comment by thibaultcha** [comment]
Indeed; glad you figured it out. Yes, I’ll add a note about this in the documentation, thank you for the suggestion.

**Comment by thibaultcha** [comment]
@cloudspeech I just added a note to the README in 2d7d7ac.
