### ISSUE TITLE
[question] should peek() return negative TTLs?

### ISSUE THREAD

**Issue by p0pr0ck5** [thibaultcha/lua-resty-mlcache#66]
Consider the following contrived example:

```
$ cat t.lua 
local mlcache = require("resty.mlcache").new("foo", "foo", {
  ttl = 0,
  neg_ttl = 0,
})

mlcache:get("foo", nil, function() return true end)
mlcache:get("bar", nil, function() return nil end)

ngx.sleep(3)

local ttl, err, value = mlcache:peek("foo")

ngx.say(ttl)
ngx.say(require("cjson").encode(value))

local ttl, err, value = mlcache:peek("bar")

ngx.say(ttl)
ngx.say(require("cjson").encode(value))
```

```
$ resty --shdict 'foo 1m' ./t.lua 
-3.0039999485016
true
-3.0039999485016
null

```

It feels a bit odd to see a negative TTL here? In a way it's a neat little hack that lets us calculate the age an object has been in cache, but it feels incongruous with the rest of the module.

**Comment by Tieske** [comment]
It's maybe slightly odd, but is does make sense to me, especially for a `peek` function that doesn't touch anything. For a `get` I can understand the request to return 0 or higher, but then the question becomes consistency in return values between the different methods.

Maybe best to align with behaviour of the shm and lru implementations?

**Comment by thibaultcha** [comment]
Well, `shm:ttl()` will return negative TTLs when the key expired. lua-resty-lrucache does not implement a a `ttl()` or `peek()` method though, and does not return the TTL from anywhere in its current API.

Maybe we should keep this as-is? In which case, we should introduce a test case for this behavior if it doesn't exist yet (along with some documentation). I will tackle it unless objections, or unless somebody else takes care of it before I do.
