### ISSUE TITLE
[feature] add extra callback layer

### ISSUE THREAD

**Issue by Tieske** [thibaultcha/lua-resty-mlcache#7]
imo an extra callback should be in between the LRU cache and SHM cache. Often you'd want the scalar values in the SHM to be converted in other structures (eg. an array/enum into a hash table) in Lua land.

If you add that in a callback it runs once, if not you'd have to test at runtime and run that test over and over again.

**Comment by thibaultcha** [comment]
> TODO:
>
>    Custom shm serializers for Lua tables when faster performance than lua-cjson is desired.

?

**Comment by hamishforbes** [comment]
The TODOs seem to have disappeared, are custom serialisers still an intended feature?

I've found it convenient to be able to at least ignore certain entries from the shm layer without having to create multiple types of cache object in your app.
e.g. when caching for ssl_certificate_by_lua you can cache the string data from reading a cert file in the shm and the cdata parsed version only in the lru level.

**Comment by thibaultcha** [comment]
Hi @hamishforbes,

> The TODOs seem to have disappeared, are custom serialisers still an intended feature?

Yes, very much! Custom callback layer and custom IPC layers are on the radar. I just thought this library would be useful enough in its current state already, those can come in future releases :)

Thanks for the kind words!

**Comment by thibaultcha** [comment]
Implemented in #29 by @jdesgats!
