### ISSUE TITLE
lock is not closed

### ISSUE THREAD

**Issue by Roycohen** [thibaultcha/lua-resty-mlcache#76]
https://github.com/thibaultcha/lua-resty-mlcache/blob/96e9d26d9ebf71933ed15ed99e5b60e508153ca1/lib/resty/mlcache.lua#L743

Seems like if we are getting into this if the lock object is not closed..
Is it true?

**Comment by thibaultcha** [comment]
If we are timing out, we are not the owner of the lock (another worker is), so it's not our responsibility to release it; we never acquired it in the first place.

**Comment by thibaultcha** [comment]
Considering this answered, closing it. If you spot an issue with this library, don't hesitate to open another ticket or even a PR. Cheers :)
