### ISSUE TITLE
decouple lru and shm caches

### ISSUE THREAD

**Issue by Tieske** [thibaultcha/lua-resty-mlcache#8]
the lru and shm caches are tightly coupled. Each lru should be able to get its own `channel`. This way multiple LRU caches for different entities can share a single SHM without interference. (eg. events for one entity triggering the callbacks for all the other entities as well)

If you use an SHM per entity, you'll be wasting a lot of memory flexibility.

**Comment by thibaultcha** [comment]
That would definitely have some value, especially considering the fundamental difference between the size unit of the shared_dict (memory) vs that of the LRU cache (number of keys). Having separate LRUs for different entities - with potentially different size averages - might help mitigate that. It can also allow one to use the `pureffi` implementation of the LRU if desired.

Mostly concerned about keeping this library easy to use though. Maybe something like:
```lua
local my_lru = resty_lru.new(100)

local val, err = cache:get("my_key", { lru = my_lru }, cb)

cache:delete("my_key", { lru = my_lru })
```

This keeps thing simple enough but invalidations are tricky, as one has to somehow pass the LRU instance to the `invalidate` method as well.

Maybe something like namespaces, to avoid having to keep a reference to the LRU instance:
```lua
local my_lru = resty_lru.new(100)
-- register LRU:
cache:add_lru("my_namespace", my_lru)

-- specify custom namespace if custom LRU is desired:
local val, err = cache:get("my_key", { namespace = "my_namespace" }, cb)

-- and invalidation:
local val, err = cache:delete("my_key", { namespace = "my_namespace" })
```

**Comment by thibaultcha** [comment]
Took a stab at this at #11.

**Comment by thibaultcha** [comment]
Done in #16
