### ISSUE TITLE
Workers launched after IPC shm LRU fail to catch up

### ISSUE THREAD

**Issue by p0pr0ck5** [thibaultcha/lua-resty-mlcache#87]
Consider the case where IPC events are regularly broadcast. Eventually, the shared memory zone will have 0 capacity, and LRU will kick in to evict the oldest events. This is certainly desirable behavior, as the lazy-delete means no code is needed for garbage collection.

However, consider the case where a new worker is spawned into existence with a previously-created memory zone (e.g., via `reload` or such), and LRU has previously been exercised on this memory zone. Since the worker's initial index is [unconditionally set to 0](https://github.com/thibaultcha/lua-resty-mlcache/blob/master/lib/resty/mlcache/ipc.lua#L65), it will attempt to replay all event since the creation of the shared memory zone. During the first call to `ipc:poll()`, [event 0 will attempt to be fetched](https://github.com/thibaultcha/lua-resty-mlcache/blob/master/lib/resty/mlcache/ipc.lua#L148), and fail as it has been LRU'd. The IPC instance idx [will then be set to 1](https://github.com/thibaultcha/lua-resty-mlcache/blob/master/lib/resty/mlcache/ipc.lua#L192), rather than the current shm idx. The poll call will also return immediately Given the default timeout of 300ms, this results in the worker attempting to replay _all_ events at a rate of roughly 3 per second; on busy systems, this results in the worker never catching up and being unable to handle any events coming into the IPC mechanism.

The end result of this behavior is that usage patterns for this library revolving around `:set` and `:delete` will only work for a finite time period, after which new worker processes cannot be created. Workarounds include restarting the master process, clearing the shm entirely (and resetting all worker indexes to 0), or having workers launched with an initial index of the current `INDEX_KEY` value, instead of 0. The lattermost feels the most reasonable approach, but I wanted to sync with you about the behavior and best path forward (given that reading from the shm cannot be done in phases where `new()` is likely called, like `init(_worker)`).

**Comment by thibaultcha** [comment]
@p0pr0ck5 Thanks for the detailed issue! Sorry I missed this. The suggested fix sounds good to me if you have some time to send a PR.

**Comment by thibaultcha** [comment]
Opened #88 with the proposed fix - reviews welcome!
