### ISSUE TITLE
resurrect_ttl doesnt work when callback returns nil, err

### ISSUE THREAD

**Issue by sauzan30** [thibaultcha/lua-resty-mlcache#89]
I created a cache instance with ttl = 30 secs
And called the get method with resurrect_ttl = 20s.

When the first callback is a success I am able to retrieve the value from L1 and L2 for the defined ttl.
I then modified the callback function to return a nil, err. 

However, the I am not getting a stale value. Instead the callback error is propagated back to the client. Shouldnt the value still remain in L2 even in an expired state after ttl expired?

**Comment by thibaultcha** [comment]
Hi,

Sorry for the delay on my side, I missed this issue. Please don't hesitate to ping in the future.

Can you share the code? The use case you are describing is covered by this test case, which is passing as expected: https://github.com/thibaultcha/lua-resty-mlcache/blob/master/t/12-resurrect-stale.t#L263-L340
